### PR TITLE
Modify scan_json.cpp to use the libary json-c

### PR DESCRIPTION
**Pull request by jgru**
Dear Simson,

this PR modifies `src/scan_json.cpp` to use the library `json-c` instead of source code under a non-free license.
Furthermore I added two files for testing the correct extraction of JSON-strings and hooked `-ljson-c` into the automake-system.
In addition I added the package `libjson-c-dev{,el} ` to the installation routines in the installation scripts stored under `etc/`.

I kindly ask you to review the newly added code.

If there are any issues with the changes, please let me know. 
If not, I will start to work on the creation of a .deb-package of bulk_extractor for the Debian package archives soon. 

Best regards
    Jan

### CODE REVIEW

**Comment by simsong** [comment]
Neat!. Let me check it out!

**Comment by simsong** [comment]
It's strange that the CI system didn't run. I'll need to add that to the main line.

**Comment by simsong** [comment]
Ah, you just check for json-c, you don't include it.

**Comment by jgru** [comment]
> Ah, you just check for json-c, you don't include it.
Ah, yes. They were in my include path on my development machine....Sorry for that. 

Furhtermor, I just reverted a change to Makefile.am to temporarily disable plugins (for my local testing purposes). 
Please note the forcely pushed update reverting this.

**Comment by simsong** [comment]
It's not clear that anybody is using the plugin tester. I'm okay with the change.

**Pull request merged**
