### PR TITLE
Adding pcre support

### PR DESCRIPTION
**Pull request by D3vil0p3r**

### CODE REVIEW

**Comment by simsong** [comment]
Why did you close this PR?

**Comment by simsong** [comment]
pcre is added for platforms that do not have RE2 libraries available. RE2 is much, much better, but it is difficult to build.

**Comment by simsong** [comment]
Oh, this PR doesn't add the flag, it just checked for the .h file...

**Comment by D3vil0p3r** [comment]
@simsong because I noted that by installing pcre dependency, I don't get the issue. Probably this PR was not needed.

**Comment by simsong** [comment]
it should detect if pcre is not installed and not create a problem.

**Pull request closed without merging**
