### PR TITLE
Fixed wrong test_be generation in bin directory

### PR DESCRIPTION
**Pull request by D3vil0p3r**

### CODE REVIEW

**Comment by simsong** [comment]
Thanks! If this works, I'll bump the version number! Do you want to be added to the contributors list?

**Comment by D3vil0p3r** [comment]
Sure. Thanks.

I tested in NixOS and it works well with this change.

**Comment by D3vil0p3r** [comment]
Hello @simsong Did you get the chance to review this PR?

**Comment by simsong** [comment]
PR is accepted. Updating the version number now.

**Comment by D3vil0p3r** [comment]
> PR is accepted. Updating the version number now.

Thank you. Once updated, I will update the package in [Nix repository](https://github.com/NixOS/nixpkgs/pull/277945)

**Comment by simsong** [comment]
What do you mean by updated? Do you need me to make a new installer? If so, where do you want it?

**Comment by D3vil0p3r** [comment]
> What do you mean by updated? Do you need me to make a new installer? If so, where do you want it?

I mean bumping the version number because I see it is still at 2.0.3 on GitHub Release
image

**Comment by simsong** [comment]
Done.

**Pull request merged**
