### PR TITLE
Added code coverage reporting using codecov.io

### PR DESCRIPTION
**Pull request by joachimmetz**
@simsong FYI this is still in draft, I'll assign the PR once ready

### CODE REVIEW

**Comment by simsong** [comment]
I added the codecov bot to this project. et me know if you need more.

**Comment by joachimmetz** [comment]
> If you set CFLAGS but not CXXFLAGS, do CFLAGS get passed to CXXFLAGS? I thought they didn't.

I think you might be right that CXXFLAGS="--coverage" needs to be added for C++

> I added the codecov bot to this project. et me know if you need more.

Thx, FYI current increment of the reports can be found here: https://codecov.io/gh/simsong/bulk_extractor/commits

**Comment by simsong** [comment]
> > If you set CFLAGS but not CXXFLAGS, do CFLAGS get passed to CXXFLAGS? I thought they didn't.
> 
> I think you might be right that CXXFLAGS="--coverage" needs to be added for C++
> 
> > I added the codecov bot to this project. et me know if you need more.
> 
> Thx, FYI current increment of the reports can be found here: https://codecov.io/gh/simsong/bulk_extractor/commits

Are you *sure* that `--coverage` is correct, and not `-fprofile-arcs -ftest-coverage` ?

**Comment by simsong** [comment]
Although I'll admit, it seems to work.

**Comment by joachimmetz** [comment]
`--coverage` is an alias

**Comment by simsong** [comment]
> `--coverage` is an alias per `man gcc'
> 
> ```
>        --coverage
>            This option is used to compile and link code instrumented for coverage analysis.  The option is a synonym for -fprofile-arcs -ftest-coverage (when compiling) and -lgcov (when linking).  See the documentation for those
>            options for more details.
> ```

Ah. There is apparently nothing that cannot be solved with another layer of indirection.

**Pull request merged**
